### ISSUE TITLE
W3 Validation

### ISSUE THREAD

**Issue by dreneuw** [asc-csa/Scisat-App#25] opened 2021-02-12 17:52 UTC
A couple of issue were encountered when running the Scisat page into the W3 validator as an html file.

- There are multiple errors caused by spaces in links as such. These issues do not come from the python file, meaning they are generated by Dash Plotly:
![image](https://user-images.githubusercontent.com/56747050/107801306-e5207e80-6d2d-11eb-9bd9-c55d86abfe4e.png)

- There are a couple color issues coming from the CSS:
![image](https://user-images.githubusercontent.com/56747050/107801705-6bd55b80-6d2e-11eb-9f6d-454a520898f8.png)

- There are a couple of elements which apparently should not be descendant of the 'a' html element:
![image](https://user-images.githubusercontent.com/56747050/107802082-e7370d00-6d2e-11eb-84ef-3f888d8f7383.png)

- The "gaz_list" id apparently has a duplicate, not inside the python code:
![image](https://user-images.githubusercontent.com/56747050/107802371-4006a580-6d2f-11eb-8157-d5035183622b.png)

- There is also an issue with a couple of attributes (persistence_* and persisted_*) that are apparently not allowed. An example:
![image](https://user-images.githubusercontent.com/56747050/107803574-c2439980-6d30-11eb-8d66-d7033d745ff4.png)

- Among other errors, there are canvas sizes error (not allowed values for width) and path elements missing a 'd' attribute:
![image](https://user-images.githubusercontent.com/56747050/107803831-21a1a980-6d31-11eb-867c-3903ba5e9666.png)
![image](https://user-images.githubusercontent.com/56747050/107803847-2b2b1180-6d31-11eb-845c-9db6ea03a185.png)

A lot of issues seem to be generated by Dash Plotly

**Comment by nfee006** [comment] 2021-04-23 17:43
Duplicate of https://github.com/asc-csa/Scisat-App/issues/106

**Closed by nfee006** 2021-04-23 17:43 UTC
